### ISSUE TITLE
Set voting and discussing time

### ISSUE THREAD

**Issue by mariomnts** [GreyWuffGames/Werewolf#194]
It would be great fot the group admin to set the time to vote and discuss. Sometimes 120 seconds is too much.

**Comment by parabola949** [comment]
@mariomnts Have you tried /config?  Admins already can.

**Comment by mariomnts** [comment]
@parabola949 I have discover this option right now but after trying to set that timers they are not working.

**Comment by parabola949** [comment]
@mariomnts You cannot change the timers mid game.  You have to wait for the next game.  Also, the day timer is the BASE time - more time is added depending on how many players are alive at the time.
var timeToAdd = Math.Max(((Players.Count(x => !x.IsDead) / 5) - 1) * 30, 60);
