### ISSUE TITLE
Repeated notification in MayorReveal

### ISSUE THREAD

**Issue by joshkurien** [GreyWuffGames/Werewolf#195]
When mayor reveals himself, the public MayorReveal string gets displayed multiple times on the group

**Comment by joshkurien** [comment]
<img width="490" alt="screen shot 2016-12-06 at 11 19 03 pm" src="https://cloud.githubusercontent.com/assets/7813196/20936956/c4cb661e-bc0a-11e6-8030-57ed1db5b0ad.png">


Basically this thing

**Comment by renyhp** [comment]
This happens when people spam the Reveal button.
I should have fixed this in commit acb51f95a40051bcd067a6dd20e5ee32e77ec22d. I'm closing this issue, but do post another issue if it happens again.
