### ISSUE TITLE
REMOVE VG ROLE

### ISSUE THREAD

**Issue by Msfabulous** [GreyWuffGames/Werewolf#200]
EVERYONE HATES THE lowly villager ROLE. When i said i wanted to petition to remove the lowly vg role, it was unanimous with all the players, nth was ever quite so unanimously agreed upon. Please. Remove the vg role. You can do a poll. Trust me there will be 100% votes to agree to remove the vg role. Pleaseeeee

**Comment by Dabadooba** [comment]
I like it... 😢

**Comment by KaiVetieno** [comment]
I vote nay. Where's the village without villagers?

**Comment by renyhp** [comment]
There are too many reasons why not removing it, for example:
1. It's a too important part of the game
2. There's no village without villagers
3. In games with too many players, we would run out of roles
4. It balances small games

**Comment by SilasSit** [comment]
You will ruin the Forbidden love achievement
