### ISSUE TITLE
bug while player can play 2 game at same time

### ISSUE THREAD

**Issue by Cojad** [GreyWuffGames/Werewolf#76]
Group A, B
—----------------
1. Start game in group A
2. flee in group A (game session still there)
3. Start game in group B
4. Now you can join A again
Then you will be playing in 2 game.

**Comment by renyhp** [comment]
Fixing this should be easy enough... so much that it makes me think that Para didn't do it because maybe that would make the command very slow, or because there is some problem about it, which I'm not thinking of. I will speak with him about this
